# Generated by Django 2.2.1 on 2020-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedioinfo',
            name='lessoninfo',
            field=models.ForeignKey(default=1, on_delete=None, to='courses.LessonInfo', verbose_name='所属章节'),
        ),
    ]
