# Generated by Django 2.2.1 on 2020-09-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_vedioinfo_lessoninfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VedioInfo',
            new_name='VideoInfo',
        ),
    ]
