# Generated by Django 2.2.1 on 2020-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], verbose_name='验证码类型'),
        ),
    ]
