# Generated by Django 2.2.1 on 2020-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200711_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlove',
            options={'verbose_name': '收藏信息', 'verbose_name_plural': '收藏信息'},
        ),
    ]
