# Generated by Django 2.2.1 on 2020-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name': '讲师信息', 'verbose_name_plural': '讲师信息'},
        ),
    ]
